version: 1

image_name: "debox-base"

image:
  base: "debian:latest"
  
  debian_components:
    - "contrib"
    - "non-free"
    - "non-free-firmware"

  packages:
    - "python3"
    - "locales"
    - "sudo"
    - "wget"
    - "gpg"
    - "ca-certificates"
    - "fontconfig"
    - "libfontconfig1"
    - "fonts-noto-core"
    - "fonts-noto-color-emoji"
    - "fonts-dejavu-core"
    - "fonts-cantarell"
    - "fonts-liberation2"
    - "libpci3"
    - "libpulse0"
    - "libcanberra-gtk3-module"
    - "bsdextrautils"
    - "xdg-utils"
    - "libcanberra-pulse"
    - "libpulse-mainloop-glib0"
